TASK_TYPE: train_dreamvideo_entrance
ENABLE: true
use_ema: false
num_workers: 6
frame_lens: [1, ]
sample_fps: [8, ]
resolution: [256, 256]
vit_resolution: [224, 224]
img_dataset: {
    'type': 'ImageCustomDataset',
    'data_list': ['data/custom/train/img_dog2.txt', ],
    'data_dir_list': ['data/images/custom/dog2', ],
    'vit_resolution': [224, 224],
    'resolution': [256, 256],
    'max_words': 6,
    "placeholder_strings": ['*']
}
embedder: {
    'type': 'FrozenOpenCLIPCustomEmbedder',
    'layer': 'penultimate',
    'vit_resolution': [224, 224],
    'pretrained': 'models/open_clip_pytorch_model.bin'
}
embedmanager: {
    'type': 'EmbeddingManager',
    'placeholder_strings': ["*"],
    'initializer_words': ["dog"],
    'per_image_tokens': False,
    'num_vectors_per_token': 1,
    'progressive_words': False
}
UNet: {
    'type': 'UNetSD_DreamVideo',
    'in_dim': 4,
    'y_dim': 1024,
    'upper_len': 128,
    'context_dim': 1024,
    'out_dim': 4,
    'dim_mult': [1, 2, 4, 4],
    'num_heads': 8,
    'default_fps': 8,
    'head_dim': 64,
    'num_res_blocks': 2,
    'dropout': 0.1,
    'misc_dropout': 0.4,
    'temporal_attention': True,
    'temporal_attn_times': 1,
    'use_checkpoint': True,
    'use_fps_condition': False,
    'use_sim_mask': False,
    'spatial_adapter_list': ['cross_attention'],
}
Diffusion: {
    'type': 'DiffusionDDIM',
    'schedule': 'linear_sd', # cosine
    'schedule_param': {
        'num_timesteps': 1000,
        'init_beta': 0.00085,
        'last_beta': 0.0120,
        'zero_terminal_snr': False,
    },
    'mean_type': 'eps',
    'loss_type': 'mse',
    'var_type': 'fixed_small',
    'rescale_timesteps': False,
    'noise_strength': 0.1
}
batch_sizes: {
    "1": 4
}
visual_train: {
    'type': 'VisualTrainDreamVideo',
    'partial_keys': [
        ['y',],
    ],
    'use_offset_noise': True,
    'guide_scale': 9.0, 
    'infer_with_custom_text': True,
    'data_list': ['data/custom/preview/subject_dog2.txt', ],
    'data_dir_list': ['data/images/custom/dog2', ],
}

Pretrain: {
    'type': pretrain_dreamvideo,
    'fix_spatial_weight': True,
    'fix_temporal_weight': True,
    'train_adapter': True,
    'grad_scale': 0.2,
    'resume_checkpoint': 'models/finetuned_modelscope.pth',
    'sd_keys_path': 'data/stable_diffusion_image_key_temporal_attention_x1.json',
}

chunk_size: 1
decoder_bs: 8
lr: 0.00001

# dreamvideo configuration
use_textInversion: True
freeze_text_embedding: True
fix_spatial_weight: True
fix_temporal_weight: True
train_adapter: True
use_clip_adapter_condition: False
use_mask_diffusion: True
gen_frames: 32
decay_mode: 'none'
negative_prompt: ''
sample_preview: True
text_embedding_path: 'workspace/dreamvideo/subjectLearningStep1/dog2_subjectLearning_step1/embeddings/text_embedding_of_*_0003000.pth'

noise_strength: 0.1
# classifier-free guidance
p_zero: 0
p_image_zero: 0
guide_scale: 9.0
num_steps: 1000

viz_interval: 100       
save_ckp_interval: 100   

# Log
log_dir: "workspace/dreamvideo/subjectLearningStep2"
log_interval: 10
seed: 8888
