TASK_TYPE: train_dreamvideo_entrance
ENABLE: true
use_ema: false
num_workers: 6
frame_lens: [32, ]
sample_fps: [8, ]
resolution: [256, 256]
vit_resolution: [224, 224]
vid_dataset: {
    'type': 'VideoCustomDataset',
    'data_list': ['data/custom/train/vid_carTurn.txt', ],
    'data_dir_list': ['data/videos/custom', ],
    'vit_resolution': [224, 224],
    'resolution': [256, 256],
    'get_random_frame': True,
    'max_words': 1,
}
embedder: {
    'type': 'FrozenOpenCLIPCustomEmbedder',
    'layer': 'penultimate',
    'vit_resolution': [224, 224],
    'pretrained': 'models/open_clip_pytorch_model.bin'
}
UNet: {
    'type': 'UNetSD_DreamVideo',
    'in_dim': 4,
    'y_dim': 1024,
    'upper_len': 128,
    'context_dim': 1024,
    'out_dim': 4,
    'dim_mult': [1, 2, 4, 4],
    'num_heads': 8,
    'default_fps': 8,
    'head_dim': 64,
    'num_res_blocks': 2,
    'dropout': 0.1,
    'misc_dropout': 0.4,
    'temporal_attention': True,
    'temporal_attn_times': 1,
    'use_checkpoint': True,
    'use_fps_condition': False,
    'use_sim_mask': False,
    'temporal_adapter_list': ['self_attention', 'cross_attention', 'feedforward'],
    'temporal_adapter_condition_dim': 1024,
}
Diffusion: {
    'type': 'DiffusionDDIM',
    'schedule': 'linear_sd', # cosine
    'schedule_param': {
        'num_timesteps': 1000,
        'init_beta': 0.00085,
        'last_beta': 0.0120,
        'zero_terminal_snr': False,
    },
    'mean_type': 'eps',
    'loss_type': 'mse',
    'var_type': 'fixed_small',
    'rescale_timesteps': False,
    'noise_strength': 0.1
}
batch_sizes: {
    "32": 1
}
visual_train: {
    'type': 'VisualTrainDreamVideo',
    'partial_keys': [
        ['y',],
    ],
    'use_offset_noise': True,
    'guide_scale': 9.0, 
    'infer_with_custom_text': True,
    'data_list': ['data/custom/preview/motion_carTurn.txt', ],
    'data_dir_list': ['data/images/motionReferenceImgs', ],
}

Pretrain: {
    'type': pretrain_dreamvideo,
    'fix_spatial_weight': True,
    'fix_temporal_weight': True,
    'train_adapter': True,
    'grad_scale': 0.2,
    'resume_checkpoint': 'models/finetuned_modelscope.pth',
    'sd_keys_path': 'data/stable_diffusion_image_key_temporal_attention_x1.json',
}

chunk_size: 1
decoder_bs: 8
lr: 0.00004  # default: 0.00001

# dreamvideo configuration
use_textInversion: False
freeze_text_embedding: False
fix_spatial_weight: True
fix_temporal_weight: True
train_adapter: True
use_clip_adapter_condition: True
gen_frames: 32
decay_mode: 'none'
negative_prompt: ''
sample_preview: True
save_latents: True

noise_strength: 0.1
# classifier-free guidance
p_zero: 0.5
p_image_zero: 0.5
guide_scale: 9.0
num_steps: 3000

viz_interval: 100       
save_ckp_interval: 100   

# Log
log_dir: "workspace/dreamvideo/motionLearning"
log_interval: 10
seed: 8888
