TASK_TYPE: inference_dreamvideo_entrance
use_fp16: True
guide_scale: 9.0
chunk_size: 2
decoder_bs: 2
max_frames: 32
scale: 8
batch_size: 1
noise_strength: 0.1
round: 1
seed: 8888
log_dir: workspace/dreamvideo/infer/joint_custom
test_list_path: data/custom/infer/joint_dog2_carTurn.txt
test_data_dir: data/images/custom/dog2
subject_cfg: configs/dreamvideo/subjectLearning/dog2_subjectLearning_step2.yaml
motion_cfg: configs/dreamvideo/motionLearning/carTurn_motionLearning.yaml
base_model: models/finetuned_modelscope.pth
identity_adapter_index: 500
motion_adapter_index: 600