TASK_TYPE: inference_dreamvideo_entrance
use_fp16: True
guide_scale: 9.0
chunk_size: 2
decoder_bs: 2
max_frames: 32
scale: 8
batch_size: 1
noise_strength: 0.1
inverse_noise_strength: 0
round: 1
seed: 8888
log_dir: workspace/dreamvideo/infer/motion_custom
test_list_path: data/custom/infer/motion_carTurn.txt
test_data_dir: data/images/motionReferenceImgs
motion_cfg: configs/dreamvideo/motionLearning/carTurn_motionLearning.yaml
base_model: models/finetuned_modelscope.pth
motion_adapter_index: 1000